---
- name: Install packages needed to compile TFS
  apt:
    state: latest
    pkg:
      - git
      - cmake
      - build-essential
      - libgmp3-dev
      - libmysqlclient-dev
      - libboost-system-dev
      - libboost-filesystem-dev
      - liblua5.2-dev
      - libpugixml-dev
      - libluajit-5.1-dev
      - libboost-iostreams-dev
      - libcrypto++-dev

- name: Download latest TFS from git
  git:
    repo: https://github.com/otland/forgottenserver.git
    dest: /home/otsmanager/forgottenserver
  become: true
  become_user: otsmanager

- name: Parse existing config.lua
  shell: grep -s mysqlPass /home/otsmanager/forgottenserver/config.lua | sed -E 's/mysqlPass = "(.*)"/\1/g'
  register: existingpass

- name: Generate random MySQL forgottenserver password
  command: openssl rand -base64 18
  register: randompass
  when: not existingpass.stdout

- set_fact:
    mysql_forgottenserver_pass: "{{ randompass.stdout if randompass is not skipped else existingpass.stdout }}"

- name: Create database user for TFS
  mysql_user:
    name: forgottenserver
    password: "{{mysql_forgottenserver_pass}}"
    priv: forgottenserver.*:ALL
    check_implicit_admin: yes

- name: Create database for TFS
  mysql_db:
    name: forgottenserver

- name: Import database for TFS
  mysql_db:
    name: forgottenserver
    state: import
    target: /home/otsmanager/forgottenserver/schema.sql

- name: Copy config.lua.dist to config.lua if necessary
  copy:
    dest: /home/otsmanager/forgottenserver/config.lua
    src: /home/otsmanager/forgottenserver/config.lua.dist
    remote_src: yes
    owner: otsmanager
    group: otsmanager

- name: Put password for database in config.lua
  lineinfile:
    dest: /home/otsmanager/forgottenserver/config.lua
    regexp: ^mysqlPass
    line: 'mysqlPass = "{{mysql_forgottenserver_pass}}"'

- name: Put server's IP address in config.lua
  lineinfile:
    dest: /home/otsmanager/forgottenserver/config.lua
    regexp: "^ip ="
    line: 'ip = "{{ansible_default_ipv4.address}}"'

- name: Create build directory
  file:
    path: /home/otsmanager/forgottenserver/build
    owner: otsmanager
    group: otsmanager
    mode: 0755
    state: directory
  become: true
  become_user: otsmanager

- name: Cmake forgottenserver source
  command: cmake ..
  args:
    chdir: /home/otsmanager/forgottenserver/build
  tags: compile
  become: true
  become_user: otsmanager

- name: Compile forgottenserver source
  command: make -j2
  args:
    chdir: /home/otsmanager/forgottenserver/build
  tags: compile
  become: true
  become_user: otsmanager
